export const EXPERTISE_CARDS = [
  {
    id: "01",
    label: "Expertise",
    title: "Social strategy",
    subtitle: "Slimme strategie. Sterke start.",
    desc: "We duiken diep in jouw merk, doelgroep en doelen. En vertalen data naar een duidelijk plan met formats die écht impact maken. Zo weet je precies waarom het werkt.",
    cta: "Meer over social strategie",
    href: "#",
    bg: "#ffffff",
    textColor: "#1a1a1a",
    numColor: "#eae6d8",
    chipBg: "#",
    chipText: "#1a1a1a",
    btnBg: "#ff3000",
    btnText: "#ffffff",
    mediaBorder: "#ff3d00",
    mediaGrad: "linear-gradient(135deg,#d4c4ac 0%,#9e7c58 100%)",
    videoSrc: "https://gethyped.b-cdn.net/MD/MD%20Loop%20Schaken.mp4",
  },
  {
    id: "02",
    label: "Expertise",
    title: "Content creation",
    subtitle: "Content die opvalt en raakt.",
    desc: "We maken content die opvalt. Blijft hangen. En jouw doelgroep raakt. Creatief, snel en energiek. Altijd met het doel voor ogen.",
    cta: "Meer over content creatie",
    href: "#",
    bg: "#ff9bf7ad",
    textColor: "#1a1a1a",
    numColor: "#ffbffc",
    chipBg: "#ffffff",
    chipText: "#1a1a1a",
    btnBg: "#ffffff",
    btnText: "#1a1a1a",
    mediaBorder: "rgba(255,255,255,0.5)",
    mediaGrad: "linear-gradient(135deg,#a855f7 0%,#3b0764 100%)",
    videoSrc: "https://gethyped.b-cdn.net/Expertises/Loop%20BTS%20comp.mp4",
  },
  {
    id: "03",
    label: "Expertise",
    title: "Activation",
    subtitle: "Zichtbaar waar en wanneer het telt.",
    desc: "De juiste content verdient het om gezien te worden. We verspreiden de content waar jouw doelgroep is. Zo raakt jouw merk de juiste mensen, precies waar en wanneer het telt.",
    cta: "Meer over activatie",
    href: "#",
    bg: "#00d798",
    textColor: "#1a1a1a",
    numColor: "#3af1bb",
    chipBg: "#ffffff",
    chipText: "#1a1a1a",
    btnBg: "#ffffff",
    btnText: "#1a1a1a",
    mediaBorder: "rgba(255,255,255,0.45)",
    mediaGrad: "linear-gradient(135deg,#5fffd8 0%,#007a55 100%)",
    videoSrc: "https://gethyped.b-cdn.net/Over%20de%20Top/overdetop-loop.mp4",
  },
  {
    id: "04",
    label: "Expertise",
    title: "Data",
    subtitle: "Inzichten die impact maken.",
    desc: "We duiken in de cijfers om te snappen wat écht werkt. En sturen jouw content scherp bij.",
    cta: "Meer over data",
    href: "#",
    bg: "#205ced",
    textColor: "#1a1a1a",
    numColor: "#0295ff",
    chipBg: "#ffffff",
    chipText: "#1a1a1a",
    btnBg: "#ffffff",
    btnText: "#1a1a1a",
    mediaBorder: "rgba(255,255,255,0.30)",
    mediaGrad: "linear-gradient(135deg,#6ea8ff 0%,#002eaa 100%)",
    videoSrc: "https://gethyped.b-cdn.net/Expertises/Data%20comp.mp4",
  },
];
